import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import LocalFont from "next/font/local";
import Navbar from "./Navbar";
import AuthProvider from "./auth/Provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500"] });
const poppins = LocalFont({
  src: "../public/fonts/poppins-regular-webfont.woff2",
  variable: "--font-poppins", // This is an alias we use for a custom css element name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className={poppins.variable}>
        <AuthProvider>
          <Navbar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
